version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.0-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: ${DOCKER_DB_NAME}
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
    ports:
      - "5432:5432"
  bot:
    container_name: bot_container
    image: grishchenkonikita/aiogram
    command: poetry run python3 /var/www/app/src/__main__.py
    volumes:
      - ./.env:/var/www/app/.env
    restart: always
    depends_on:
      - postgres

volumes:
  pg-data:
